import type {
  User,
  Post,
  Product,
  Order,
  Comment,
  Brand,
  Review,
  Article,
  VetReview,
  Animal,
} from './types';

export const MOCK_BRANDS: Brand[] = [
  // Row 1
  {
    id: 3,
    name: 'Drools',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/1a3a8f?text=drools&font=montserrat',
  },
  {
    id: 7,
    name: 'Lara',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/e3232c?text=Lara&font=montserrat',
  },
  {
    id: 4,
    name: 'Me-O',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/e8642c?text=Me-O&font=montserrat',
  },
  {
    id: 9,
    name: 'Reflex Plus',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/4a9f3f?text=Reflex&font=montserrat',
  },
  {
    id: 14,
    name: 'Reflex',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/c83232?text=Reflex&font=montserrat',
  },
  {
    id: 1,
    name: 'Royal Canin',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/e3000b?text=Royal+Canin&font=montserrat',
  },
  {
    id: 6,
    name: 'SmartHeart',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/d41920?text=SmartHeart&font=montserrat',
  },
  // Row 2
  {
    id: 17,
    name: 'Versele-Laga',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/006838?text=Versele-Laga&font=montserrat',
  },
  {
    id: 5,
    name: 'Whiskas',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/5b2d8e?text=Whiskas&font=montserrat',
  },
  {
    id: 18,
    name: 'BonaCibo',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/c41230?text=BonaCibo&font=montserrat',
  },
  {
    id: 19,
    name: 'Bunny',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/f7941e?text=Bunny&font=montserrat',
  },
  {
    id: 20,
    name: 'Classic Pets',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/2e6930?text=Classic+Pets&font=montserrat',
  },
  {
    id: 21,
    name: 'Friskies',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/cc0000?text=Friskies&font=montserrat',
  },
  {
    id: 22,
    name: 'Golden Kat Litter',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/c8a415?text=Golden+Kat&font=montserrat',
  },
  // Row 3
  {
    id: 23,
    name: 'Goodies',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/1a1a1a?text=Goodies&font=montserrat',
  },
  {
    id: 15,
    name: 'JerHigh',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/e31e24?text=JerHigh&font=montserrat',
  },
  {
    id: 24,
    name: 'Lazy Lady',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/666666?text=Lazy+Lady&font=montserrat',
  },
  {
    id: 25,
    name: 'Meat Up',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/1a1a1a?text=Meat+Up&font=montserrat',
  },
  {
    id: 26,
    name: 'Inaba',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/d41920?text=Inaba&font=montserrat',
  },
  {
    id: 27,
    name: 'Micho',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/8dc63f?text=micho&font=montserrat',
  },
  {
    id: 28,
    name: 'Nekko',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/1a1a1a?text=Nekko&font=montserrat',
  },
  // Row 4
  {
    id: 29,
    name: 'Paws',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/00b0c8?text=PAWS&font=montserrat',
  },
  {
    id: 2,
    name: 'Pedigree',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/ffc107?text=Pedigree&font=montserrat',
  },
  {
    id: 30,
    name: 'ProDiet',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/1a1a1a?text=ProDiet&font=montserrat',
  },
  {
    id: 31,
    name: 'Purina',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/cc0000?text=Purina&font=montserrat',
  },
  {
    id: 32,
    name: 'Sheba',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/c89632?text=Sheba&font=montserrat',
  },
  {
    id: 10,
    name: 'Spectrum',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=SPECTRUM&font=montserrat',
  },
  {
    id: 33,
    name: 'Temptations',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/f5a623?text=Temptations&font=montserrat',
  },
  // Row 5
  {
    id: 34,
    name: 'Toro Toro',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/0088cc?text=Toro+Toro&font=montserrat',
  },
  // Hidden brands (kept for backward compatibility with existing products)
  {
    id: 8,
    name: 'Kaniva',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=Kaniva&font=montserrat',
  },
  {
    id: 11,
    name: 'Trendline',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=Trendline&font=montserrat',
  },
  {
    id: 12,
    name: 'Harvest Luck',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=Harvest+Luck&font=montserrat',
  },
  {
    id: 13,
    name: 'Bonnie',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=Bonnie&font=montserrat',
  },
  {
    id: 16,
    name: 'PetBhai Essentials',
    logoUrl: 'https://placehold.co/200x100/FFFFFF/333333?text=PetBhai+Essentials&font=montserrat',
  },
];

const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    author: 'Aisha R.',
    rating: 5,
    comment: 'My cat absolutely loves this. The tuna flavor is her favorite!',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    author: 'Jamal K.',
    rating: 4,
    comment: "Good quality food, my cat's coat has become much shinier.",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Me-O Adult Cat Food Tuna',
    category: 'Cat Food',
    price: 2450,
    imageUrl: '/images/products/product-1.webp',
    description:
      'A delicious and nutritious tuna-flavored dry food for adult cats of all breeds. Enriched with vitamins and minerals for a healthy life. A popular choice for cat owners in Bangladesh.',
    weight: '7kg',
    brandId: 4,
    rating: 4.8,
    reviews: MOCK_REVIEWS,
    searchTags: ['বিড়াল', 'খাবার', 'ক্যাট ফুড', 'cat food', 'biral', 'khabar', 'meo', 'tuna'],
  },
  {
    id: 2,
    name: 'Drools Optimum Performance Puppy Food',
    category: 'Dog Food',
    price: 1150,
    imageUrl: '/images/products/product-2.webp',
    description:
      'Specially formulated for puppies to support their growth and development with essential nutrients, prebiotics and probiotics. Highly recommended by vets.',
    weight: '3kg',
    brandId: 3,
    rating: 4.5,
    reviews: [
      {
        id: 3,
        author: 'Fahim C.',
        rating: 5,
        comment: 'My puppy is growing so fast and healthy with this food.',
        date: new Date().toISOString(),
      },
    ],
    searchTags: [
      'কুকুর',
      'খাবার',
      'পাপি',
      'ডগ ফুড',
      'dog food',
      'kukur',
      'khabar',
      'puppy',
      'drools',
    ],
  },
  {
    id: 3,
    name: 'Whiskas Ocean Fish (Adult)',
    category: 'Cat Food',
    price: 690,
    imageUrl: '/images/products/product-3.webp',
    description:
      'Whiskas Ocean Fish is a complete and balanced dry food for adult cats. It supports healthy skin and a shiny coat. Very popular in Dhaka.',
    weight: '1.2kg',
    brandId: 5,
    rating: 4.6,
    reviews: [],
    searchTags: ['whiskas', 'cat food', 'fish', 'ocean fish', 'biral', 'khabar'],
  },
  {
    id: 4,
    name: 'Pedigree Adult Dry Dog Food (Chicken & Veg)',
    category: 'Dog Food',
    price: 3150,
    imageUrl: '/images/products/product-4.webp',
    description:
      'A complete and balanced meal for your adult dog, packed with chicken and vegetable goodness for a healthy immune system.',
    weight: '10kg',
    brandId: 2,
    rating: 4.7,
    reviews: [],
    searchTags: [
      'কুকুর',
      'খাবার',
      'পেডিগ্রি',
      'dog food',
      'kukur',
      'khabar',
      'adult',
      'chicken',
      'pedigree',
    ],
  },
  {
    id: 5,
    name: 'Royal Canin Persian Adult Cat Food',
    category: 'Cat Food',
    price: 3100,
    imageUrl: '/images/products/product-5.webp',
    description:
      'Tailor-made nutrition for Persian cats to maintain their long, beautiful coats and digestive health. Almond-shaped kibble for easy grasping.',
    weight: '2kg',
    brandId: 1,
    rating: 4.9,
    reviews: [
      {
        id: 4,
        author: 'Sadia A.',
        rating: 5,
        comment: 'The only food my Persian will eat. Her coat has never looked better!',
        date: new Date().toISOString(),
      },
    ],
    searchTags: [
      'বিড়াল',
      'খাবার',
      'রয়াল ক্যানিন',
      'পার্সিয়ান',
      'cat food',
      'biral',
      'khabar',
      'royal canin',
      'persian',
    ],
  },
  {
    id: 6,
    name: 'SmartHeart Adult Cat Food Chicken & Tuna',
    category: 'Cat Food',
    price: 520,
    imageUrl: '/images/products/product-6.webp',
    description:
      'SmartHeart Adult Cat Food is formulated to meet adult cat nutritional requirements. Enriched with DHA and EPA.',
    weight: '1.2kg',
    brandId: 6,
    rating: 4.5,
    reviews: [],
    searchTags: ['smartheart', 'cat food', 'chicken', 'tuna', 'biral', 'khabar'],
  },
  {
    id: 7,
    name: 'Lara Adult Cat Food Salmon',
    category: 'Cat Food',
    price: 1150,
    imageUrl: '/images/products/product-7.webp',
    description:
      'Delicious chunks with salmon for adult cats. Let your cat enjoy this crispy food. A premium choice available in Bangladesh.',
    weight: '2kg',
    brandId: 7,
    rating: 4.4,
    reviews: [],
    searchTags: ['lara', 'cat food', 'salmon', 'biral', 'khabar', 'fish'],
  },
  {
    id: 8,
    name: 'SmartHeart Power Pack Puppy',
    category: 'Dog Food',
    price: 1450,
    imageUrl: '/images/products/product-8.webp',
    description:
      'High energy formula for active puppies. Promotes muscle mass and proper structure.',
    weight: '3kg',
    brandId: 6,
    rating: 4.7,
    reviews: [],
    searchTags: ['smartheart', 'dog food', 'puppy', 'power pack', 'kukur', 'khabar'],
  },
  {
    id: 9,
    name: 'Cat Litter Bentonite (Apple Scent)',
    category: 'Cat Supplies',
    price: 320,
    imageUrl: '/images/products/product-9.webp',
    description: 'Premium clumping cat litter with apple scent. Dust-free and super absorbent.',
    weight: '5L',
    brandId: 4,
    rating: 4.3,
    reviews: [],
    searchTags: ['litter', 'bali', 'cat litter', 'bathroom', 'biral'],
  },
  {
    id: 10,
    name: 'Himalaya Erina EP Shampoo',
    category: 'Grooming',
    price: 330,
    imageUrl: '/images/products/product-10.webp',
    description: 'Controls ectoparasites like ticks, fleas and lice. Prevents skin infections.',
    weight: '200ml',
    brandId: 2,
    rating: 4.6,
    reviews: [],
    searchTags: ['shampoo', 'ticks', 'fleas', 'grooming', 'gosol'],
  },
  {
    id: 11,
    name: 'Heavy-Duty Nylon Dog Leash',
    category: 'Dog Supplies',
    price: 350,
    imageUrl: '/images/products/product-11.webp',
    description:
      'A strong and reliable 6-foot nylon leash, perfect for daily walks and training sessions.',
    weight: '150g',
    brandId: 3,
    rating: 4.9,
    reviews: [],
    searchTags: ['বেল্ট', 'রশি', 'লিচ', 'belt', 'leash', 'roshi', 'walk'],
  },
  {
    id: 12,
    name: 'Interactive Feather Wand for Cats',
    category: 'Cat Supplies',
    price: 140,
    imageUrl: '/images/products/product-12.webp',
    description:
      'Engage your cat in hours of fun with this interactive feather wand. Great for exercise and bonding.',
    weight: '50g',
    brandId: 4,
    rating: 4.4,
    reviews: [],
    searchTags: ['খেলনা', 'বিড়াল', 'খেলনা', 'toy', 'cat toy', 'khelna', 'biral'],
  },
  {
    id: 13,
    name: 'Durable Rubber Chew Bone for Dogs',
    category: 'Dog Supplies',
    price: 240,
    imageUrl: '/images/products/product-13.webp',
    description:
      'A tough, durable chew toy designed to withstand even the most enthusiastic chewers. Promotes dental health.',
    weight: '200g',
    brandId: 3,
    rating: 4.6,
    reviews: [],
    searchTags: ['খেলনা', 'হাড়', 'কুকুর', 'toy', 'bone', 'chew', 'kukur', 'khelna'],
  },
  {
    id: 14,
    name: 'Stainless Steel Pet Bowl (Anti-Skid)',
    category: 'Dog Supplies',
    price: 220,
    imageUrl: '/images/products/product-14.webp',
    description:
      'High-quality stainless steel bowl with a rubber base to prevent sliding and tipping. Easy to clean.',
    weight: 'Medium',
    brandId: 16,
    stockStatus: 'in-stock',
    rating: 4.5,
    reviews: [],
    searchTags: ['bowl', 'barty', 'food bowl', 'water bowl', 'kukur', 'biral'],
  },
  {
    id: 15,
    name: 'Whiskas Pocket Ocean Fish',
    category: 'Cat Food',
    price: 75,
    imageUrl: '/images/products/product-15.webp',
    description: 'Small trial pack of Whiskas Ocean Fish. Perfect for a single meal or treat.',
    weight: '85g',
    brandId: 5,
    rating: 4.2,
    reviews: [],
    searchTags: ['whiskas', 'cat food', 'small', 'packet', 'biral', 'khabar'],
  },
  {
    id: 16,
    name: 'Cat Scratching Post (Sisal Rope)',
    category: 'Cat Supplies',
    price: 780,
    imageUrl: '/images/products/product-16.webp',
    description:
      'Save your furniture! Durable sisal rope scratching post that cats love to scratch. Includes a hanging toy.',
    weight: '1.5kg',
    brandId: 16,
    rating: 4.7,
    reviews: [],
    searchTags: ['scratcher', 'scratch', 'post', 'toy', 'biral', 'khelna'],
  },
  {
    id: 17,
    name: 'Soft Fleece Pet Bed (Washable)',
    category: 'Dog Supplies',
    price: 850,
    imageUrl: '/images/products/product-17.webp',
    description:
      'Ultra-soft fleece bed for cats and small dogs. Machine washable and very cozy for winter.',
    weight: 'Size M',
    brandId: 16,
    rating: 4.8,
    reviews: [],
    searchTags: ['bed', 'sleep', 'bichana', 'cushion', 'dog', 'cat'],
  },
  {
    id: 18,
    name: 'Reflex Plus Adult Cat Food (Chicken)',
    category: 'Cat Food',
    price: 3450,
    imageUrl: '/images/products/product-18.webp',
    description:
      'Super premium cat food with chicken. Xylo-oligosaccharides (XOS) super prebiotics for digestion.',
    weight: '8kg',
    brandId: 9,
    rating: 4.9,
    reviews: [],
    searchTags: ['reflex', 'plus', 'cat food', 'chicken', 'biral', 'khabar'],
  },
  {
    id: 19,
    name: 'Bonnie Adult Cat Food (Chicken)',
    category: 'Cat Food',
    price: 3850,
    imageUrl: '/images/products/product-19.webp',
    description:
      'Bulk pack of Bonnie Adult Cat Food. Great value for multi-cat households. Chicken flavor.',
    weight: '10kg',
    brandId: 13,
    rating: 4.4,
    reviews: [],
    searchTags: ['bonnie', 'cat food', 'chicken', 'bulk', 'biral', 'khabar'],
  },
  {
    id: 20,
    name: 'SmartHeart Adult Dog Food (Roast Beef)',
    category: 'Dog Food',
    price: 1180,
    imageUrl: '/images/products/product-20.webp',
    description: 'SmartHeart Dog Food with Roast Beef flavor. Irresistible taste for your dog.',
    weight: '3kg',
    brandId: 6,
    rating: 4.6,
    reviews: [],
    searchTags: ['smartheart', 'dog food', 'beef', 'roast beef', 'kukur', 'khabar'],
  },
  {
    id: 21,
    name: 'Drools Chicken and Egg Adult Dog Food',
    category: 'Dog Food',
    price: 980,
    imageUrl: '/images/products/product-21.webp',
    description:
      'Drools Chicken and Egg formula provides complete nutrition. Real chicken meat and egg.',
    weight: '3kg',
    brandId: 3,
    rating: 4.5,
    reviews: [],
    searchTags: ['drools', 'dog food', 'chicken', 'egg', 'kukur', 'khabar'],
  },
  {
    id: 22,
    name: 'Reflex High Quality Adult Dog Food (Lamb & Rice)',
    category: 'Dog Food',
    price: 1380,
    imageUrl: '/images/products/product-22.webp',
    description: 'Reflex Dog Food with Lamb & Rice is easy to digest and perfect for adult dogs.',
    weight: '3kg',
    brandId: 14,
    rating: 4.7,
    reviews: [],
    searchTags: ['reflex', 'dog food', 'lamb', 'rice', 'kukur', 'khabar'],
  },
  {
    id: 23,
    name: 'JerHigh Meat as Meals',
    category: 'Dog Food',
    price: 650,
    imageUrl: '/images/products/product-23.webp',
    description:
      'JerHigh Meat as Meals is a premium semi-moist dog food suitable for all breeds. Soft texture.',
    weight: '500g',
    brandId: 15,
    rating: 4.9,
    reviews: [],
    searchTags: ['jerhigh', 'dog food', 'soft', 'treat', 'kukur', 'khabar'],
  },
  {
    id: 24,
    name: 'Bentonite Cat Litter (Lemon/Coffee)',
    category: 'Cat Supplies',
    price: 310,
    imageUrl: '/images/products/product-24.webp',
    description:
      'High-quality Bentonite Cat Litter with pleasant scent (Lemon or Coffee). Strong clumping action.',
    weight: '5L',
    brandId: 16,
    rating: 4.3,
    reviews: [],
    searchTags: ['litter', 'bali', 'cat litter', 'lemon', 'coffee', 'biral'],
  },
  {
    id: 25,
    name: 'Plastic Litter Box with Rim',
    category: 'Cat Supplies',
    price: 390,
    imageUrl: '/images/products/product-25.webp',
    description:
      'Durable plastic litter box with removable rim to prevent spillage. Easy to clean.',
    weight: 'Medium',
    brandId: 16,
    rating: 4.4,
    reviews: [],
    searchTags: ['litter box', 'tray', 'toilet', 'cat', 'biral', 'box'],
  },
  {
    id: 26,
    name: 'Self-cleaning Slicker Brush',
    category: 'Grooming',
    price: 260,
    imageUrl: '/images/products/product-26.webp',
    description:
      'Easily remove loose fur and tangles. One-click self-cleaning mechanism makes grooming a breeze.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.7,
    reviews: [],
    searchTags: ['brush', 'comb', 'fur', 'grooming', 'cat', 'dog', 'hair'],
  },
  {
    id: 27,
    name: 'Pet Carrier Cage (Airline Approved)',
    category: 'Cat Supplies',
    price: 1350,
    imageUrl: '/images/products/product-27.webp',
    description:
      'Sturdy pet carrier cage suitable for cats and small dogs. Good ventilation and secure lock.',
    weight: 'Size S',
    brandId: 16,
    rating: 4.8,
    reviews: [],
    searchTags: ['carrier', 'cage', 'travel', 'transport', 'cat', 'dog'],
  },
  {
    id: 28,
    name: 'Pet Nail Clipper',
    category: 'Grooming',
    price: 160,
    imageUrl: '/images/products/product-28.webp',
    description:
      'Sharp stainless steel blades for precise cutting. Safety guard to prevent over-cutting.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.5,
    reviews: [],
    searchTags: ['nail', 'clipper', 'cut', 'grooming', 'cat', 'dog', 'nok'],
  },
  {
    id: 29,
    name: 'Adjustable Nylon Neck Collar with Bell',
    category: 'Cat Supplies',
    price: 85,
    imageUrl: '/images/products/product-29.webp',
    description: 'Colorful nylon collar with a cute bell. Adjustable size for cats and small dogs.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.3,
    reviews: [],
    searchTags: ['collar', 'belt', 'bell', 'ghonti', 'cat', 'dog', 'neck'],
  },
  {
    id: 30,
    name: 'Inaba Ciao Churu Tuna Creamy Cat Treats',
    category: 'Cat Food',
    price: 190,
    originalPrice: 230,
    discount: 17,
    imageUrl: '/images/products/product-30.webp',
    description:
      'The #1 lickable puree treat in Bangladesh. Made with real deep-sea tuna and green tea extract for hydration and irresistible taste.',
    weight: '4 x 14g (56g)',
    brandId: 26,
    rating: 4.9,
    reviews: [],
    searchTags: [
      'inaba',
      'ciao',
      'churu',
      'creamy',
      'treat',
      'cat treat',
      'বিড়াল',
      'ট্রিট',
      'চুরু',
      'biral',
      'khabar',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 65,
  },
  {
    id: 31,
    name: 'Whiskas Tuna in Jelly Wet Cat Food Pouch',
    category: 'Cat Food',
    price: 85,
    originalPrice: 100,
    discount: 15,
    imageUrl: '/images/products/product-31.webp',
    description:
      'Tender tuna flakes in appetizing jelly, formulated with balanced nutrition for adult cats. Highly affordable pocket meal.',
    weight: '85g',
    brandId: 5,
    rating: 4.8,
    reviews: [],
    searchTags: [
      'whiskas',
      'pouch',
      'wet food',
      'tuna',
      'cat food',
      'হুইস্কাস',
      'বিড়াল',
      'খাবার',
      'পাউচ',
      'biral',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 80,
  },
  {
    id: 32,
    name: 'SmartHeart Creamy Cat Treats Salmon',
    category: 'Cat Food',
    price: 160,
    originalPrice: 190,
    discount: 16,
    imageUrl: '/images/products/product-32.webp',
    description:
      'Creamy lickable salmon puree treats packed with Omega-3 and Omega-6 for shiny skin and lustrous coat.',
    weight: '4 x 15g (60g)',
    brandId: 6,
    rating: 4.7,
    reviews: [],
    searchTags: [
      'smartheart',
      'creamy',
      'salmon',
      'treat',
      'cat treat',
      'স্মার্টহার্ট',
      'বিড়াল',
      'ট্রিট',
      'খাবার',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 50,
  },
  {
    id: 33,
    name: 'Pedigree Dentastix Daily Oral Care Treats for Small Dogs',
    category: 'Dog Food',
    price: 240,
    originalPrice: 280,
    discount: 14,
    imageUrl: '/images/products/product-33.webp',
    description:
      'Clinically proven to reduce tartar and plaque build-up by up to 80%. Unique X-shape design cleans teeth down to the gum line.',
    weight: '110g (7 sticks)',
    brandId: 2,
    rating: 4.8,
    reviews: [],
    searchTags: [
      'pedigree',
      'dentastix',
      'dental',
      'dog treat',
      'chew',
      'পেডিগ্রি',
      'কুকুর',
      'ট্রিট',
      'ডেন্টাস্টিংক্স',
      'kukur',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 45,
  },
  {
    id: 34,
    name: 'Meat Up Real Chicken Dog Crunchy Biscuits Jar',
    category: 'Dog Food',
    price: 280,
    originalPrice: 340,
    discount: 18,
    imageUrl: '/images/products/product-34.webp',
    description:
      'Crunchy bone-shaped biscuits baked with real chicken, calcium, and vitamins to support strong teeth, gums, and bones.',
    weight: '500g',
    brandId: 25,
    rating: 4.6,
    reviews: [],
    searchTags: [
      'meat up',
      'biscuits',
      'cookie',
      'dog treat',
      'মিট আপ',
      'কুকুর',
      'বিস্কুট',
      'ট্রিট',
      'kukur',
      'khabar',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 35,
  },
  {
    id: 35,
    name: 'Temptations Tasty Chicken Flavour Crunchy Cat Treats',
    category: 'Cat Food',
    price: 290,
    originalPrice: 350,
    discount: 17,
    imageUrl: '/images/products/product-35.webp',
    description:
      'Irresistible dual-textured cat treats with a crunchy shell and savory soft center. Under 2 calories per treat.',
    weight: '85g',
    brandId: 33,
    rating: 4.9,
    reviews: [],
    searchTags: [
      'temptations',
      'crunchy',
      'chicken',
      'cat treat',
      'টেম্পটেশন',
      'বিড়াল',
      'ট্রিট',
      'খাবার',
      'biral',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 40,
  },
  {
    id: 36,
    name: 'PetBhai Ergonomic Sifting Cat Litter Shovel & Scoop',
    category: 'Cat Supplies',
    price: 75,
    originalPrice: 100,
    discount: 25,
    imageUrl: '/images/products/product-36.webp',
    description:
      'Durable non-toxic plastic sifting shovel designed for fast clumps separation and easy litter cleaning.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.6,
    reviews: [],
    searchTags: [
      'litter scoop',
      'shovel',
      'cleaning',
      'cat litter',
      'চামচ',
      'লিটার স্কুপ',
      'বিড়াল',
      'cat',
      'scoop',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 70,
  },
  {
    id: 37,
    name: 'PetBhai Double Anti-Slip Feeding Bowl for Dogs & Cats',
    category: 'Accessories',
    price: 140,
    originalPrice: 180,
    discount: 22,
    imageUrl: '/images/products/product-37.webp',
    description:
      'Convenient dual food and water bowl combo with non-skid base. Made of durable, food-grade plastic for easy cleaning.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.7,
    reviews: [],
    searchTags: [
      'bowl',
      'feeder',
      'water bowl',
      'double bowl',
      'বাটি',
      'খাবারের বাটি',
      'পেট বোল',
      'cat',
      'dog',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 55,
  },
  {
    id: 38,
    name: 'PetBhai Eco-Friendly Waste Poop Bag Dispenser with 30 Bags',
    category: 'Dog Supplies',
    price: 120,
    originalPrice: 160,
    discount: 25,
    imageUrl: '/images/products/product-38.webp',
    description:
      'Portable bone-shaped bag dispenser with secure leash clip and 2 refill rolls (30 leak-proof scented clean-up bags).',
    weight: '1 dispenser + 2 rolls',
    brandId: 16,
    rating: 4.8,
    reviews: [],
    searchTags: [
      'poop bag',
      'waste bag',
      'dispenser',
      'dog walking',
      'পুপ ব্যাগ',
      'কুকুর',
      'বর্জ্য ব্যাগ',
      'dog',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 60,
  },
  {
    id: 39,
    name: 'PetBhai Plush Catnip Play Mouse Toy (Pack of 3)',
    category: 'Cat Supplies',
    price: 150,
    originalPrice: 200,
    discount: 25,
    imageUrl: '/images/products/product-39.webp',
    description:
      'Set of 3 plush toy mice stuffed with natural catnip to stimulate hunting instincts, exercise, and playful batting.',
    weight: '3 units',
    brandId: 16,
    rating: 4.8,
    reviews: [],
    searchTags: [
      'mouse toy',
      'catnip',
      'plush toy',
      'cat toy',
      'খেলনা',
      'বিড়াল খেলনা',
      'ইঁদুর',
      'cat',
      'biral',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 50,
  },
  {
    id: 40,
    name: 'Bioline Gentle Grooming & Tear Stain Wipes for Pets (100 pcs)',
    category: 'Grooming',
    price: 260,
    originalPrice: 320,
    discount: 19,
    imageUrl: '/images/products/product-40.webp',
    description:
      'Hypoallergenic wipes infused with natural aloe vera and chamomile to clean eyes, ears, and paws safely without stinging.',
    weight: '100 wipes',
    brandId: 16,
    rating: 4.7,
    reviews: [],
    searchTags: [
      'wipes',
      'tear stain',
      'ear wipes',
      'grooming',
      'bioline',
      'ওয়াইপস',
      'গ্রুমিং',
      'বিড়াল',
      'কুকুর',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 40,
  },
  {
    id: 41,
    name: 'PetBhai Fine-Tooth Flea, Tick & Dust Removal Steel Comb',
    category: 'Grooming',
    price: 95,
    originalPrice: 130,
    discount: 27,
    imageUrl: '/images/products/product-41.webp',
    description:
      'Close stainless steel teeth effectively trap fleas, ticks, and loose debris. Smooth rounded tips protect pet skin.',
    weight: '1 unit',
    brandId: 16,
    rating: 4.6,
    reviews: [],
    searchTags: [
      'flea comb',
      'tick comb',
      'steel comb',
      'grooming',
      'চিরুনি',
      'উকুন চিরুনি',
      'গ্রুমিং',
      'cat',
      'dog',
    ],
    stockStatus: 'in-stock',
    stockQuantity: 75,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Aisha Rahman',
    email: 'aisha@example.com',
    profilePictureUrl: 'https://picsum.photos/seed/aisha/200',
    wishlist: [2, 4],
    orderHistory: [],
    favorites: [1, 3],
    isPlusMember: true,
  },
  {
    id: 2,
    name: 'Jamal Khan',
    email: 'jamal@example.com',
    profilePictureUrl: 'https://picsum.photos/seed/jamal/200',
    wishlist: [],
    orderHistory: [],
    favorites: [],
    isPlusMember: false,
  },
];

const MOCK_COMMENTS: Comment[] = [
  {
    id: 1,
    author: {
      id: 2,
      name: 'Jamal Khan',
      profilePictureUrl: 'https://picsum.photos/seed/jamal/200',
    },
    text: 'Great advice! I was wondering about this for my cat.',
    likes: [1],
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    replies: [
      {
        id: 101,
        author: {
          id: 1,
          name: 'Aisha Rahman',
          profilePictureUrl: 'https://picsum.photos/seed/aisha/200',
        },
        text: 'Same here, thanks for sharing!',
        likes: [2],
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 1,
    author: {
      id: 1,
      name: 'Aisha Rahman',
      profilePictureUrl: 'https://picsum.photos/seed/aisha/200',
    },
    content:
      'Just switched my cat to Royal Canin and her coat has never been shinier! Anyone else have good experiences with this brand?',
    imageUrl: './images/desi-breeds/desi_cat_1_1781109714663.png',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    likes: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    comments: MOCK_COMMENTS,
  },
  {
    id: 2,
    author: {
      id: 2,
      name: 'Jamal Khan',
      profilePictureUrl: 'https://picsum.photos/seed/jamal/200',
    },
    content:
      '🐕 Pro tip for new dog owners: Consistency is key in training! Start with basic commands like "sit" and "stay" and practice daily. My German Shepherd learned these in just 2 weeks. What training tips do you have?',
    imageUrl: './images/desi-breeds/desi_dog_2_1781109705659.png',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: [1, 3, 5, 7],
    comments: [],
  },
  {
    id: 3,
    author: {
      id: 3,
      name: 'Fatima Akter',
      profilePictureUrl: 'https://picsum.photos/seed/fatima/200',
    },
    content:
      'Looking for recommendations for a good vet in Dhanmondi area. My kitten needs her first vaccination. Any suggestions would be greatly appreciated! 🐱💉',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: [1, 2],
    comments: [
      {
        id: 2,
        author: {
          id: 1,
          name: 'Aisha Rahman',
          profilePictureUrl: 'https://picsum.photos/seed/aisha/200',
        },
        text: 'I highly recommend Dr. Kabir at Dhaka Pet Hospital! Very gentle with kittens.',
        likes: [3],
        timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        replies: [],
      },
    ],
  },
];

const MOCK_VET_REVIEWS: VetReview[] = [
  {
    id: 1,
    author: 'Aisha R.',
    rating: 5,
    comment: 'Dr. Ahmed was so gentle with my cat and very knowledgeable. Highly recommend!',
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    author: 'Jamal K.',
    rating: 5,
    comment:
      "Excellent online consultation. Dr. Islam gave me clear advice for my senior cat's diet.",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_VETS: any[] = [
  {
    id: 1,
    name: 'Dr. Fatima Ahmed',
    specialization: 'General Pet Health',
    clinicName: 'Paws & Claws Clinic',
    address: 'House 15, Road 7, Block G, Banani, Dhaka',
    phone: '+8801712-345678',
    imageUrl: 'https://picsum.photos/seed/vet1/200/200',
    availability: 'Available Today',
    bio: 'Dr. Fatima Ahmed is a compassionate veterinarian with over 10 years of experience in small animal medicine. She graduated from the Bangladesh Agricultural University and has a special interest in dermatology and internal medicine.',
    qualifications: ['DVM, BAU', 'Member of BSAVA'],
    services: [
      { name: 'General Consultation', price: 800, type: 'in-clinic' },
      { name: 'Online Consultation', price: 600, type: 'online' },
      { name: 'Annual Vaccination', price: 1500, type: 'in-clinic' },
    ],
    reviews: MOCK_VET_REVIEWS,
  },
  {
    id: 2,
    name: 'Dr. Kabir Hossain',
    specialization: 'Canine Specialist',
    clinicName: 'Dhaka Pet Hospital',
    address: '21/A, Dhanmondi Road 2, Dhaka',
    phone: '+8801812-345679',
    imageUrl: 'https://picsum.photos/seed/vet2/200/200',
    availability: 'Offline',
    bio: 'Dr. Kabir Hossain is a leading canine specialist in Dhaka, with a focus on orthopedic surgery and behavioral therapy. His state-of-the-art facility provides top-notch care for dogs of all breeds and sizes.',
    qualifications: [
      'DVM, Chittagong Veterinary and Animal Sciences University',
      'Advanced Certification in Canine Surgery',
    ],
    services: [
      { name: 'Specialist Consultation', price: 1200, type: 'in-clinic' },
      { name: 'Orthopedic Surgery', price: 25000, type: 'in-clinic' },
    ],
    reviews: [],
  },
  {
    id: 3,
    name: 'Dr. Nazia Islam',
    specialization: 'Feline Health & Nutrition',
    clinicName: 'The Cat Care Center',
    address: '123/B, Gulshan Avenue, Gulshan 2, Dhaka',
    phone: '+8801912-345680',
    imageUrl: 'https://picsum.photos/seed/vet3/200/200',
    availability: 'Available Now',
    bio: 'Dr. Nazia Islam is a dedicated feline practitioner who runs a cats-only clinic to ensure a stress-free environment for her patients. She is an expert in feline nutrition and preventative care.',
    qualifications: ['DVM, SYLVET', 'Certified Feline Nutritionist'],
    services: [
      { name: 'Online Feline Consultation', price: 700, type: 'online' },
      { name: 'In-Clinic Feline Check-up', price: 1000, type: 'in-clinic' },
      { name: 'Dental Cleaning', price: 3500, type: 'in-clinic' },
    ],
    reviews: [MOCK_VET_REVIEWS[1]],
  },
  {
    id: 4,
    name: 'Dr. Asaduzzaman Noor',
    specialization: 'Avian & Exotic Pets',
    clinicName: 'Birds & Exotics Care',
    address: 'Plot 5, Section 6, Mirpur, Dhaka',
    phone: '+8801755-123456',
    imageUrl: 'https://picsum.photos/seed/vet4/200/200',
    availability: 'Available Today',
    bio: 'Dr. Noor is one of the few specialists in Bangladesh focusing on birds and exotic pets. Whether you have a parrot, rabbit, or turtle, Dr. Noor offers expert advice on diet, habitat, and health.',
    qualifications: ['DVM, BAU', 'Masters in Wildlife Medicine'],
    services: [
      { name: 'Online Bird Consultation', price: 600, type: 'online' },
      { name: 'Exotic Pet Checkup', price: 1000, type: 'in-clinic' },
      { name: 'Beak & Nail Trimming', price: 400, type: 'in-clinic' },
    ],
    reviews: [],
  },
  {
    id: 5,
    name: 'Dr. Rebeka Sultana',
    specialization: 'Veterinary Dermatology',
    clinicName: 'Vet Care BD',
    address: 'Sector 4, Road 13, Uttara, Dhaka',
    phone: '+8801611-987654',
    imageUrl: 'https://picsum.photos/seed/vet5/200/200',
    availability: 'Available Now',
    bio: 'Skin issues are very common in our humid climate. Dr. Rebeka Sultana specializes in diagnosing and treating complicated skin conditions, allergies, and fungal infections in dogs and cats.',
    qualifications: ['DVM, SAU', 'PhD in Veterinary Dermatology'],
    services: [
      { name: 'Online Skin Consultation', price: 800, type: 'online' },
      { name: 'Dermatology Screening', price: 1500, type: 'in-clinic' },
      { name: 'Allergy Testing', price: 2000, type: 'in-clinic' },
    ],
    reviews: [],
  },
  {
    id: 6,
    name: 'Dr. Imtiaz Ahmed',
    specialization: 'General Medicine & Surgery',
    clinicName: 'Chattogram Pet Hospital',
    address: 'O.R. Nizam Road, Chittagong',
    phone: '+8801819-556677',
    imageUrl: 'https://picsum.photos/seed/vet6/200/200',
    availability: 'Available Today',
    bio: 'Based in Chittagong, Dr. Imtiaz Ahmed brings 8 years of experience in treating small animals. He is well-known for his calm demeanor and accurate diagnosis. He is now available for online consultations nationwide.',
    qualifications: ['DVM, CVASU', 'Member of BCVA'],
    services: [
      { name: 'Telemedicine Session', price: 500, type: 'online' },
      { name: 'General Health Check', price: 700, type: 'in-clinic' },
      { name: 'Spay/Neuter Surgery', price: 4000, type: 'in-clinic' },
    ],
    reviews: [],
  },
  {
    id: 7,
    name: 'Dr. Nyla Khan',
    specialization: 'Pet Nutrition & Behavior',
    clinicName: 'Pet Life Hospital',
    address: 'Bashundhara R/A, Dhaka',
    phone: '+8801913-445566',
    imageUrl: 'https://picsum.photos/seed/vet7/200/200',
    availability: 'Available Now',
    bio: 'Dr. Nyla Khan focuses on the holistic well-being of pets. If your pet is a picky eater, overweight, or showing behavioral issues like aggression or anxiety, Dr. Nyla can provide a customized plan online.',
    qualifications: ['DVM, BAU', 'Certified Clinical Pet Nutritionist'],
    services: [
      { name: 'Diet & Nutrition Plan', price: 1000, type: 'online' },
      { name: 'Behavioral Therapy (Online)', price: 1200, type: 'online' },
      { name: 'Weight Management', price: 800, type: 'in-clinic' },
    ],
    reviews: [],
  },
];

export const MOCK_ARTICLES: Article[] = [];

export const MOCK_ANIMALS: any[] = [
  {
    id: 1,
    name: 'Sundori',
    species: 'Cat',
    breed: 'Desi / Local',
    age: 'Adult',
    location: 'Dhaka',
    imageUrl: './images/desi-breeds/desi_cat_4_1781109766371.png',
    status: 'Available',
    description:
      'A lovely and affectionate local street cat looking for a forever home. Very friendly and great with kids. She loves napping in the sun.',
    sex: 'Female',
    color: 'Brown Tabby',
    vaccinated: true,
    spayedNeutered: true,
    postedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    name: 'Lalu',
    species: 'Dog',
    breed: 'Desi / Pariah',
    age: 'Young',
    location: 'Chittagong',
    imageUrl: './images/desi-breeds/desi_dog_1_1781109694683.png',
    status: 'Available',
    description:
      'Energetic, loyal, and playful Desi dog. Needs a loving family with space to run around. Very protective and smart.',
    sex: 'Male',
    color: 'Golden Brown',
    vaccinated: true,
    spayedNeutered: false,
    postedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// NOTE: Groomers, Trainers, Pet Sitters data has been removed.
// These services show "Coming Soon" on the ServicesPage.
// When ready, implement backend API endpoints for these services.

export const BANGLADESH_DISTRICTS: string[] = [
  'Bagerhat',
  'Bandarban',
  'Barguna',
  'Barishal',
  'Bhola',
  'Bogura',
  'Brahmanbaria',
  'Chandpur',
  'Chapainawabganj',
  'Chattogram',
  'Chuadanga',
  'Cumilla',
  "Cox's Bazar",
  'Dhaka',
  'Dinajpur',
  'Faridpur',
  'Feni',
  'Gaibandha',
  'Gazipur',
  'Gopalganj',
  'Habiganj',
  'Jamalpur',
  'Jashore',
  'Jhalokati',
  'Jhenaidah',
  'Joypurhat',
  'Khagrachhari',
  'Khulna',
  'Kishoreganj',
  'Kurigram',
  'Kushtia',
  'Lakshmirpur',
  'Lalmonirhat',
  'Madaripur',
  'Magura',
  'Manikganj',
  'Meherpur',
  'Moulvibazar',
  'Munshiganj',
  'Mymensingh',
  'Naogaon',
  'Narail',
  'Narayanganj',
  'Narsingdi',
  'Natore',
  'Netrokona',
  'Nilphamari',
  'Noakhali',
  'Pabna',
  'Panchagarh',
  'Patuakhali',
  'Pirojpur',
  'Rajbari',
  'Rajshahi',
  'Rangamati',
  'Rangpur',
  'Satkhira',
  'Shariatpur',
  'Sherpur',
  'Sirajganj',
  'Sunamganj',
  'Sylhet',
  'Tangail',
  'Thakurgaon',
];

export const BANGLADESH_DIVISIONS: string[] = [
  'Barishal',
  'Chattogram',
  'Dhaka',
  'Khulna',
  'Mymensingh',
  'Rajshahi',
  'Rangpur',
  'Sylhet',
];
